name: Set labels

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - ready_for_review

  workflow_dispatch:

concurrency:
  group: ci-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-pr:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Add Folder Labels
        uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          sync-labels: true

      - name: Add Environment Labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            bug
            enhancement
